Vagrant::Config.run do |config|

  config.vm.box_url = "http://vmbox.metacpan.org/mcwheezy_vm_debian_002.box"
  config.vm.box = "mcwheezy"

  # currently the puppet setup is designed to be bootstrapped
  # by these shell scripts rather than simply applied

end
